version: '3.8'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    command: >
      postgres -c 'fsync=off'
                -c 'full_page_writes=off'
                -c 'synchronous_commit=off'
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

volumes:
  data:
